server:
  port: 8061

#mybatis-plus映射mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gpdi.wireless.domain
spring:
  application:
    name: sharing-sphere-server
